#!/usr/bin/env bash
set -ex

case $1 in

  start)
		dpkg -x /var/vcap/packages/newrelic-infra-bosh/*.deb /var/vcap/packages/newrelic-infra-bosh/apt
		export PATH="/var/vcap/packages/newrelic-infra-bosh/apt/usr/bin:$PATH"
		export LD_LIBRARY_PATH="/var/vcap/packages/newrelic-infra-bosh/apt/usr/lib:$LD_LIBRARY_PATH"
		export INCLUDE_PATH="/var/vcap/packages/newrelic-infra-bosh/apt/usr/include:$INCLUDE_PATH"
		export CPATH="$INCLUDE_PATH"
		export CPPPATH="$INCLUDE_PATH"

		newrelic-infra -config /var/vcap/jobs/newrelic-infra-bosh/newrelic-infra.yml &
		
		pidof newrelic-infra | cut -f 1 -d \ > /var/vcap/sys/run/newrelic-infra-bosh/pid
    ;;

  stop)

		kill -2 $(pidof newrelic-infra)
    ;;

  *)
    echo "Usage: newrelic-infra-bosh {start|stop}"

    ;;

esac
